name: Tests
on: push
jobs:
  setup-and-test:
    name: Setup & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - run: npm install
      - run: npm test
